### ISSUE TITLE
Doesn't support contenttype route overrides

### ISSUE THREAD

**Issue by zigpress** [AppoloDev/bolt-seo#20]
If I add a contenttype override in routes.yaml to hide the slug of a contenttype in URLs, something like this:

```
pagebinding:
  path: /{slugOrId}
  methods: [GET|POST]
  defaults:
    contentTypeSlug: page
    _controller: Bolt\Controller\Frontend\DetailController::record
```

I find that the seo fields (e.g. seo.title etc) are not available in my template. A dump of the seo variable reveals that the seoData property is null.

If I comment out the override in routes.yaml, and revisit the page (using the old URL containing the contenttype slug), the seoData property is populated and the fields are available.
